name: Deploy Java App to Amazon EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Rama a desplegar'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Configurar JDK 21 y cache Gradle
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '21'
          cache: gradle

      - name: Hacer ejecutable el wrapper de Gradle
        run: chmod +x gradlew

      - name: Construir con ShadowJar
        run: ./gradlew clean shadowJar

      - name: Buscar y mover el JAR a raíz
        id: mover_jar
        run: |
          JAR_PATH=$(find app/build/libs -name "*-all.jar" | head -n 1)
          if [ -z "$JAR_PATH" ]; then
            echo "No se encontró un archivo JAR"
            exit 1
          fi
          JAR_NAME=$(basename "$JAR_PATH")
          mv "$JAR_PATH" "$JAR_NAME"
          echo "Archivo JAR listo: $JAR_NAME"
          echo "jar_name=$JAR_NAME" >> $GITHUB_OUTPUT

      - name: Crear estructura de carpetas en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /opt/apps/backend/scripts
            sudo chmod -R 755 /opt/apps/backend

      - name: Copiar scripts de despliegue a EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "deploy-scripts/"
          target: "/opt/apps/backend/scripts/"
          overwrite: true

      - name: Asignar permisos a los scripts en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo chmod +x /opt/apps/backend/scripts/pre-deploy
            sudo chmod +x /opt/apps/backend/scripts/post-deploy

      - name: Ejecutar script pre-deploy (detener app previa)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Ejecutando pre-deploy..."
            sudo /opt/apps/backend/scripts/pre-deploy

      - name: Copiar JAR generado al servidor EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "${{ steps.mover_jar.outputs.jar_name }}"
          target: "/opt/apps/backend/"
          overwrite: true

      - name: Verificar JAR en EC2 (opcional)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Confirmando JAR en servidor:"
            ls -lh /opt/apps/backend/

      - name: Ejecutar post-deploy (iniciar app con systemd)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Iniciando app con post-deploy..."
            sudo /opt/apps/backend/scripts/post-deploy
